export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://collabden-backend.onrender.com';

export const API_ENDPOINTS = {
  AUTH: {
    SIGNUP: `${API_BASE_URL}/api/v1/user/signup`,
    LOGIN: `${API_BASE_URL}/api/v1/user/login`,
    PROFILE: `${API_BASE_URL}/api/v1/user/profile`,
    VERIFY: `${API_BASE_URL}/api/v1/user/verify`,
    RESEND_VERIFY: `${API_BASE_URL}/api/v1/user/resend-verify`,
    FORGOT_PASSWORD: `${API_BASE_URL}/api/v1/user/forgot-password`,
    RESET_PASSWORD: `${API_BASE_URL}/api/v1/user/reset-password`,
    GOOGLE_AUTH: `${API_BASE_URL}/api/v1/user/auth/google`,
    GOOGLE_CALLBACK: `${API_BASE_URL}/api/v1/user/auth/google/callback`,
    ONBOARDING: `${API_BASE_URL}/api/v1/user/onboarding`,
  },
  ADMIN_AUTH: {
    LOGIN: `${API_BASE_URL}/api/v1/admin/auth/login`,
    VERIFY_2FA: `${API_BASE_URL}/api/v1/admin/auth/verify-2fa`,
    RESEND_2FA: `${API_BASE_URL}/api/v1/admin/auth/resend-2fa`,
    FORGOT_PASSWORD: `${API_BASE_URL}/api/v1/admin/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE_URL}/api/v1/admin/auth/reset-password`,
    ME: `${API_BASE_URL}/api/v1/admin/auth/me`,
    // Next.js proxy routes — these go through /app/api/admin/auth/* to set HTTP-only cookies
    PROXY_LOGIN: `/api/admin/auth/login`,
    PROXY_VERIFY_2FA: `/api/admin/auth/verify-2fa`,
    // Backward compatibility aliases
    ALL_USERS: `${API_BASE_URL}/api/v1/admin/users/all-users`,
    USER_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}`,
    USER_ACTIVITY: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/activity`,
    USER_REPORTS: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/reports`,
    USER_AUDIT_HISTORY: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/audit-history`,
    USER_NOTES: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/notes`,
    MODERATE_USER: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/moderate`,
  },
  ADMIN_USERS: {
    ALL_USERS: `${API_BASE_URL}/api/v1/admin/users/all-users`,
    USER_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}`,
    USER_ACTIVITY: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/activity`,
    USER_REPORTS: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/reports`,
    USER_AUDIT_HISTORY: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/audit-history`,
    USER_NOTES: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/notes`,
    MODERATE_USER: (id: string) => `${API_BASE_URL}/api/v1/admin/users/all-users/${id}/moderate`,
  },
  ADMIN_PERMISSIONS: {
    ROLES: `${API_BASE_URL}/api/v1/admin/permissions`,
    AVAILABLE_ROLES: `${API_BASE_URL}/api/v1/admin/permissions/available`,
    ROLES_HISTORY: `${API_BASE_URL}/api/v1/admin/permissions/history`,
    ROLE_DETAIL: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}`,
    UPDATE_ROLE: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}`,
    ADD_ROLE_PERMISSIONS: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}/permissions/add`,
    REMOVE_ROLE_PERMISSIONS: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}/permissions/remove`,
    ADD_ROLE_MODULES: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}/modules/add`,
    REMOVE_ROLE_MODULES: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}/modules/remove`,
    DELETE_ROLE: (role: string) => `${API_BASE_URL}/api/v1/admin/permissions/${role}`,
  },
  ADMIN_ACCOUNTS: {
    LIST: `${API_BASE_URL}/api/v1/admin/users`,
    DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/users/${id}`,
    UPDATE_ROLE: (id: string) => `${API_BASE_URL}/api/v1/admin/users/${id}/role`,
    DEACTIVATE: (id: string) => `${API_BASE_URL}/api/v1/admin/users/${id}/deactivate`,
    ACCESS_LOGS: `${API_BASE_URL}/api/v1/admin/users/all-users`,
  },
  ADMIN_PROJECTS: {
    ALL_PROJECTS: `${API_BASE_URL}/api/v1/admin/projects/all-projects`,
    PROJECT_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/projects/all-projects/${id}`,
    PROJECT_ACTIVITY: (id: string) => `${API_BASE_URL}/api/v1/admin/projects/all-projects/${id}/activity`,
    REPORTS: `${API_BASE_URL}/api/v1/admin/projects/reports`,
    REPORT_DETAIL: (reportId: string) => `${API_BASE_URL}/api/v1/admin/projects/reports/${reportId}`,
    UPDATE_REPORT_STATUS: (projectId: string, reportId: string) => `${API_BASE_URL}/api/v1/admin/projects/all-projects/${projectId}/reports/${reportId}/status`,
    UPDATE_GLOBAL_REPORT_STATUS: (reportId: string) => `${API_BASE_URL}/api/v1/admin/projects/reports/${reportId}/status`,
    PROJECT_NOTES: (id: string) => `${API_BASE_URL}/api/v1/admin/projects/all-projects/${id}/notes`,
    PROJECT_AUDIT_HISTORY: (id: string) => `${API_BASE_URL}/api/v1/admin/projects/all-projects/${id}/audit`,
    MODERATE_PROJECT: (id: string) => `${API_BASE_URL}/api/v1/admin/projects/all-projects/${id}/moderate`,
  },
  ADMIN_MARKETPLACE: {
    ROOT: `${API_BASE_URL}/api/v1/admin/marketplace`,
    REPORTS: `${API_BASE_URL}/api/v1/admin/marketplace/reports`,
    REPORT_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/marketplace/reports/${id}`,
    UPDATE_REPORT_STATUS: (id: string) => `${API_BASE_URL}/api/v1/admin/marketplace/reports/${id}/status`,
    NOTES: `${API_BASE_URL}/api/v1/admin/marketplace/notes`,
    AUDIT: `${API_BASE_URL}/api/v1/admin/marketplace/audit`,
    COLLABORATOR_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/marketplace/collaborators/${id}`,
    MODERATE_COLLABORATOR: (id: string) => `${API_BASE_URL}/api/v1/admin/marketplace/collaborators/${id}/moderate`,
    MODERATE_PROJECT: (id: string) => `${API_BASE_URL}/api/v1/admin/marketplace/projects/${id}/moderate`,
  },
  ADMIN_AGREEMENTS: {
    ROOT: `${API_BASE_URL}/api/v1/admin/agreements`,
    REPORTS: `${API_BASE_URL}/api/v1/admin/agreements/reports`,
    REPORT_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/agreements/reports/${id}`,
    UPDATE_REPORT_STATUS: (id: string) => `${API_BASE_URL}/api/v1/admin/agreements/reports/${id}/status`,
    NOTES: `${API_BASE_URL}/api/v1/admin/agreements/notes`,
    AUDIT: `${API_BASE_URL}/api/v1/admin/agreements/audit`,
    DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/agreements/${id}`,
    ACTIVITY: (id: string) => `${API_BASE_URL}/api/v1/admin/agreements/${id}/activity`,
  },
  ADMIN_TRANSACTIONS: {
    LIST: `${API_BASE_URL}/api/v1/admin/transactions`,
    DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/transactions/${id}`,
  },
  ADMIN_ESCROW: {
    LIST: `${API_BASE_URL}/api/v1/admin/escrow`,
    DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/escrow/${id}`,
  },
  ADMIN_DISPUTES: {
    LIST: `${API_BASE_URL}/api/v1/admin/disputes`,
    DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}`,
    ASSIGN: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/assign`,
    UPDATE_STATUS: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/status`,
    NOTES: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/notes`,
    MESSAGES: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/messages`,
    EVIDENCE_REQUESTS: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/evidence-requests`,
    REQUEST_EVIDENCE: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/request-evidence`,
    DECISION: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/decision`,
    AUDIT_LOGS: (id: string) => `${API_BASE_URL}/api/v1/admin/disputes/${id}/audit-logs`,
  },
  ADMIN_FINANCE: {
    WITHDRAWALS: `${API_BASE_URL}/api/v1/admin/finance/withdrawals`,
    WITHDRAWAL_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/finance/withdrawals/${id}`,
    SUBSCRIPTION_PAYMENTS: `${API_BASE_URL}/api/v1/admin/finance/subscription-payments`,
    SUBSCRIPTION_PAYMENT_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/admin/finance/subscription-payments/${id}`,
  },
  ADMIN_PAYMENTS: {
    REPORTS: `${API_BASE_URL}/api/v1/admin/payments/reports`,
    AUDIT: `${API_BASE_URL}/api/v1/admin/payments/audit`,
  },
  DASHBOARD: {
    ROOT: `${API_BASE_URL}/api/v1/dashboard`,
  },
  ADMIN_DASHBOARD: {
    ROOT: `${API_BASE_URL}/api/v1/dashboard/admin`,
    USER_STATS: `${API_BASE_URL}/api/v1/dashboard/admin/stats/users`,
    PROJECT_STATS: `${API_BASE_URL}/api/v1/dashboard/admin/stats/projects`,
    PENDING_STATS: `${API_BASE_URL}/api/v1/dashboard/admin/stats/pending`,
    PENDING_ACTIONS: `${API_BASE_URL}/api/v1/dashboard/admin/pending-actions`,
    ACTIVITIES: `${API_BASE_URL}/api/v1/dashboard/admin/activities`,
  },
  NOTIFICATIONS: {
    LIST: `${API_BASE_URL}/api/v1/notifications`,
    READ_ALL: `${API_BASE_URL}/api/v1/notifications/read-all`,
    READ_ONE: (id: string) => `${API_BASE_URL}/api/v1/notifications/${id}/read`,
  },
  PROJECTS: {
    LIST: `${API_BASE_URL}/api/v1/projects`,
    CREATE: `${API_BASE_URL}/api/v1/projects`,
    DETAIL: (id: string) => `${API_BASE_URL}/api/v1/projects/${id}`,
    UPDATE: (id: string) => `${API_BASE_URL}/api/v1/projects/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/api/v1/projects/${id}`,
    INVITE: (id: string) => `${API_BASE_URL}/api/v1/projects/${id}/invite`,
    REMOVE_COLLABORATOR: (projectId: string, collaboratorId: string) => 
      `${API_BASE_URL}/api/v1/projects/${projectId}/collaborators/${collaboratorId}`,
    METADATA: (id: string) => `${API_BASE_URL}/api/v1/projects/${id}/metadata`,
  },
  AGREEMENTS: {
    UPLOAD: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/agreements`,
    LIST: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/agreements`,
    UPDATE: (projectId: string, id: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/agreements/${id}`,
    STATUS: (projectId: string, id: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/agreements/${id}/status`,
    SIGN: (projectId: string, id: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/agreements/${id}/sign`,
    ESIGN: (projectId: string, id: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/agreements/${id}/esign`,
  },
  CONNECTIONS: {
    SEND_REQUEST: `${API_BASE_URL}/api/v1/user/connections/request`,
    RESPOND_REQUEST: (id: string) => `${API_BASE_URL}/api/v1/user/connections/request/${id}`,
    LIST: `${API_BASE_URL}/api/v1/user/connections`,
    LIST_PENDING: `${API_BASE_URL}/api/v1/user/connections/pending`,
  },
  WAITLIST: {
    LIST: `${API_BASE_URL}/api/v1/waitlist`,
    JOIN: `${API_BASE_URL}/api/v1/waitlist`,
    DOWNLOAD: `${API_BASE_URL}/api/v1/waitlist/download`,
  },
  PROFILE: {
    UPDATE: `${API_BASE_URL}/api/v1/user/profile`,
    EMAIL: `${API_BASE_URL}/api/v1/user/profile/email`,
    PHONE: `${API_BASE_URL}/api/v1/user/profile/phone`,
    PASSWORD: `${API_BASE_URL}/api/v1/user/profile/password`,
    AVATAR: `${API_BASE_URL}/api/v1/user/profile/avatar`,
    COMPLETENESS: `${API_BASE_URL}/api/v1/user/profile/completeness`,
    BROWSE: `${API_BASE_URL}/api/v1/user/profile/browse`,
    DETAIL: (userId: string) => `${API_BASE_URL}/api/v1/user/profile/${userId}`,
    ENDORSE: (userId: string) => `${API_BASE_URL}/api/v1/user/profile/${userId}/endorsements`,
    PORTFOLIO: (userId: string) => `${API_BASE_URL}/api/v1/user/profile/portfolio/${userId}`,
    UPDATE_PORTFOLIO: (projectId: string) => `${API_BASE_URL}/api/v1/user/profile/portfolio/${projectId}`,
    PROJECT_ENDORSEMENT: (projectId: string) => `${API_BASE_URL}/api/v1/user/profile/portfolio/${projectId}/endorsements`,
  },
  MESSAGING: {
    SEND_REQUEST: `${API_BASE_URL}/api/v1/messaging/requests`,
    RESPOND_REQUEST: (id: string) => `${API_BASE_URL}/api/v1/messaging/requests/${id}`,
    LIST_REQUESTS: `${API_BASE_URL}/api/v1/messaging/requests`,
    LIST_CHATS: `${API_BASE_URL}/api/v1/messaging/chats`,
    MESSAGES: (chatId: string) => `${API_BASE_URL}/api/v1/messaging/chats/${chatId}/messages`,
    READ: (chatId: string) => `${API_BASE_URL}/api/v1/messaging/chats/${chatId}/read`,
    REACTION: (messageId: string) => `${API_BASE_URL}/api/v1/messaging/messages/${messageId}/reactions`,
    ARCHIVE: (chatId: string) => `${API_BASE_URL}/api/v1/messaging/chats/${chatId}/archive`,
    DELETE_CHAT: (chatId: string) => `${API_BASE_URL}/api/v1/messaging/chats/${chatId}`,
  },
  PAYMENTS: {
    WALLET: `${API_BASE_URL}/api/v1/payments/wallet`,
    TRANSACTIONS: `${API_BASE_URL}/api/v1/payments/transactions`,
    FUND_INITIALIZE: `${API_BASE_URL}/api/v1/payments/fund/initialize`,
    FUND_VERIFY: `${API_BASE_URL}/api/v1/payments/fund/verify`,
    BANKS: `${API_BASE_URL}/api/v1/payments/banks`,
    BANK_ACCOUNTS: `${API_BASE_URL}/api/v1/payments/bank-accounts`,
    BANK_ACCOUNT_DETAIL: (id: string) => `${API_BASE_URL}/api/v1/payments/bank-accounts/${id}`,
    WITHDRAW: `${API_BASE_URL}/api/v1/payments/withdraw`,
    WITHDRAWALS: `${API_BASE_URL}/api/v1/payments/withdrawals`,
  },
  SECURITY: {
    SETUP_2FA: `${API_BASE_URL}/api/v1/user/security/2fa/setup`,
    VERIFY_2FA: `${API_BASE_URL}/api/v1/user/security/2fa/verify`,
    LOGOUT_ALL: `${API_BASE_URL}/api/v1/user/security/logout-all`,
    DEACTIVATE: `${API_BASE_URL}/api/v1/user/security/deactivate`,
    DELETE: `${API_BASE_URL}/api/v1/user/security/delete`,
    DATA_EXPORT: `${API_BASE_URL}/api/v1/user/security/data-export`,
    EXPORT_STATUS: (id: string) => `${API_BASE_URL}/api/v1/user/security/data-export/${id}`,
    SUPPORT: `${API_BASE_URL}/api/v1/user/security/support-request`,
  },
  COLLABORATORS: {
    LIST: `${API_BASE_URL}/api/v1/user/collaborators`,
    SKILLS: `${API_BASE_URL}/api/v1/user/collaborators/skills`,
    GENRES: `${API_BASE_URL}/api/v1/user/collaborators/genres`,
    AVAILABILITY: `${API_BASE_URL}/api/v1/user/collaborators/availability`,
    DETAIL: (userId: string) => `${API_BASE_URL}/api/v1/user/collaborators/${userId}`,
  },
  NOTIFICATION_SETTINGS: {
    ROOT: `${API_BASE_URL}/api/v1/notification-settings`,
  },
  SUBSCRIPTIONS: {
    PLANS: `${API_BASE_URL}/api/v1/subscriptions/plans`,
    ME: `${API_BASE_URL}/api/v1/subscriptions/me`,
    SUBSCRIBE: `${API_BASE_URL}/api/v1/subscriptions/subscribe`,
    CANCEL: `${API_BASE_URL}/api/v1/subscriptions/cancel`,
    REACTIVATE: `${API_BASE_URL}/api/v1/subscriptions/reactivate`,
    BILLING_HISTORY: `${API_BASE_URL}/api/v1/subscriptions/billing/history`,
    INVOICE: (id: string) => `${API_BASE_URL}/api/v1/subscriptions/billing/invoices/${id}`,
    INVOICE_PDF: (id: string) => `${API_BASE_URL}/api/v1/subscriptions/billing/invoices/${id}/pdf`,
    PAYMENT_METHODS: `${API_BASE_URL}/api/v1/subscriptions/payment-methods`,
    DEFAULT_PAYMENT_METHOD: (id: string) => `${API_BASE_URL}/api/v1/subscriptions/payment-methods/${id}/default`,
    DELETE_PAYMENT_METHOD: (id: string) => `${API_BASE_URL}/api/v1/subscriptions/payment-methods/${id}`,
  },
  ESCROW: {
    MY_PAYMENTS: `${API_BASE_URL}/api/v1/projects/escrow/my-payments`,
    DISPUTES_RESOLVE: (milestoneId: string) => `${API_BASE_URL}/api/v1/projects/escrow/disputes/${milestoneId}/resolve`,
    CONFIGURE: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow`,
    DETAIL: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow`,
    STATUS: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/status`,
    APPROVE_PROPOSAL: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/approve`,
    FUND: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/fund`,
    PAYMENT_HISTORY: (projectId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/payments`,
    MILESTONE_DETAIL: (projectId: string, milestoneId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/milestones/${milestoneId}`,
    MILESTONE_SUBMIT: (projectId: string, milestoneId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/milestones/${milestoneId}/submit`,
    MILESTONE_APPROVE: (projectId: string, milestoneId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/milestones/${milestoneId}/approve`,
    MILESTONE_DISPUTE: (projectId: string, milestoneId: string) => `${API_BASE_URL}/api/v1/projects/${projectId}/escrow/milestones/${milestoneId}/dispute`,
  },
};

export interface API_RESPONSE<T = unknown> {
  success: boolean;
  message?: string;
  data?: T;
  error?: string;
}

export interface USER_PROFILE {
  id: string;
  email: string;
  isVerified: boolean;
}
